//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookseeker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bookseeker : DbContext
    {
        public Bookseeker()
            : base("name=Bookseeker")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_Keyword_Link> Book_Keyword_Link { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Keywords> Keywords { get; set; }
    }
}
